[package]
name = "systest"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
build = "build.rs"

[dependencies]
libssh2-sys = { path = "../libssh2-sys" }
libc = "0.2"

[build-dependencies]
ctest2 = "0.4"
